await message.delete()
embed=discord.Embed(title="Заглавие", url="http://Ссылка_заглавие.dom", description="Описание заглавия")
embed.set_author(name="Автор", url="http://Ссылка_автора.dom", icon_url="http://Иконка_автора.png")
embed.set_image(url="http://Картинка_рядом_с_заглавием.png")
embed.set_thumbnail(url="http://Большая_картинка.png")
embed.add_field(name="Заглавие пункта списка 1", value="Текст пункта списка 1", inline=False)
embed.add_field(name="Заглавие пункта списка 2", value="Текст пункта списка 2", inline=True)
embed.set_footer(text="Низ ембеда")
await message.channel.send(embed=embed)